[alias]
run-wasm = "run --release --package run-wasm --"

[build]
rustdocflags = [
    #"--cfg=",
    "-Dabsolute_paths_not_starting_with_crate",
    "-Dambiguous_associated_items",
    "-Danonymous_parameters",
    "-Darithmetic_overflow",
    "-Dasm_sub_register",
    "-Dbad_asm_style",
    "-Dbare_trait_objects",
    "-Dbindings_with_variant_name",
    "-Dbreak_with_label_and_loop",
    "-Dclashing_extern_declarations",
    "-Dcoherence_leak_check",
    "-Dconflicting_repr_hints",
    "-Dconst_evaluatable_unchecked",
    "-Dconst_item_mutation",
    "-Ddead_code",
    "-Ddeprecated",
    "-Ddeprecated_in_future",
    "-Dderef_into_dyn_supertrait",
    "-Dderef_nullptr",
    "-Dellipsis_inclusive_range_patterns",
    "-Dexplicit_outlives_requirements",
    "-Dexported_private_dependencies",
    "-Dforbidden_lint_groups",
    "-Dfunction_item_references",
    "-Dill_formed_attribute_input",
    "-Dincomplete_features",
    "-Dincomplete_include",
    "-Dineffective_unstable_trait_impl",
    "-Dinline_no_sanitize",
    "-Dinvalid_doc_attributes",
    "-Dinvalid_type_param_default",
    "-Dinvalid_value",
    "-Dirrefutable_let_patterns",
    "-Dkeyword_idents",
    "-Dlarge_assignments",
    "-Dlate_bound_lifetime_arguments",
    "-Dlegacy_derive_helpers",
    "-Dmacro_expanded_macro_exports_accessed_by_absolute_paths",
    "-Dmacro_use_extern_crate",
    "-Dmeta_variable_misuse",
    "-Dmissing_abi",
    "-Dmutable_transmutes",
    "-Dnamed_asm_labels",
    "-Dnon_shorthand_field_patterns",
    "-Dno_mangle_const_items",
    "-Dno_mangle_generic_items",
    "-Doverlapping_range_endpoints",
    "-Dpatterns_in_fns_without_body",
    "-Dpub_use_of_private_extern_crate",
    "-Drenamed_and_removed_lints",
    "-Drust_2021_incompatible_or_patterns",
    "-Dwarnings",
]

rustflags = [
    "--cfg",
    "reqwest_unstable",
    "-Dabsolute_paths_not_starting_with_crate",
    "-Dambiguous_associated_items",
    "-Danonymous_parameters",
    "-Darithmetic_overflow",
    "-Dasm_sub_register",
    "-Dbad_asm_style",
    "-Dbare_trait_objects",
    "-Dbindings_with_variant_name",
    "-Dbreak_with_label_and_loop",
    "-Dclashing_extern_declarations",
    "-Dcoherence_leak_check",
    "-Dconflicting_repr_hints",
    "-Dconst_evaluatable_unchecked",
    "-Dconst_item_mutation",
    "-Ddead_code",
    "-Ddeprecated",
    "-Ddeprecated_in_future",
    "-Dderef_into_dyn_supertrait",
    "-Dderef_nullptr",
    "-Dellipsis_inclusive_range_patterns",
    "-Dexplicit_outlives_requirements",
    "-Dexported_private_dependencies",
    "-Dforbidden_lint_groups",
    "-Dfunction_item_references",
    "-Dill_formed_attribute_input",
    "-Dincomplete_features",
    "-Dincomplete_include",
    "-Dineffective_unstable_trait_impl",
    "-Dinline_no_sanitize",
    "-Dinvalid_doc_attributes",
    "-Dinvalid_type_param_default",
    "-Dinvalid_value",
    "-Dirrefutable_let_patterns",
    "-Dkeyword_idents",
    "-Dlarge_assignments",
    "-Dlate_bound_lifetime_arguments",
    "-Dlegacy_derive_helpers",
    "-Dmacro_expanded_macro_exports_accessed_by_absolute_paths",
    "-Dmacro_use_extern_crate",
    "-Dmeta_variable_misuse",
    "-Dmissing_abi",
    "-Dmutable_transmutes",
    "-Dnamed_asm_labels",
    "-Dnon_shorthand_field_patterns",
    "-Dno_mangle_const_items",
    "-Dno_mangle_generic_items",
    "-Doverlapping_range_endpoints",
    "-Dpatterns_in_fns_without_body",
    "-Dpub_use_of_private_extern_crate",
    "-Drenamed_and_removed_lints",
    "-Drust_2021_incompatible_or_patterns",
    "-Dwarnings",
    "-Clink-args=-Wl,-rpath,/usr/local/lib,-rpath,/Library/Frameworks/GStreamer.framework/Versions/1.0/lib",
]
